import type { AppUser, BiographyProject, Chapter, ExportJob, InterviewSession, PersonMention, Recording, TimelineEvent } from './types';

type Store = { projects: Map<string, BiographyProject>; transcripts: Map<string, { id: string; recordingId: string; rawText: string; correctedText: string; language: string; processingStatus: string }> };
const globalStore = globalThis as typeof globalThis & { __keepsakeStore?: Store };

function createId(prefix: string) { return `${prefix}_${crypto.randomUUID()}`; }

function seedProject(): BiographyProject {
  const now = new Date().toISOString();
  return {
    id: 'project_maya', ownerId: 'demo-user', title: "Maya's Story", storytellerName: 'Maya Sharma', storytellerRelationship: 'Grandmother', preferredLanguage: 'en', status: 'in_progress', coverImageUrl: null, createdAt: now, updatedAt: now,
    consent: { storytellerName: 'Maya Sharma', recordingConsent: true, aiProcessingConsent: true, voiceGenerationConsent: false, consentedAt: now },
    interviews: [{ id: 'session_first', title: 'Growing up in Kathmandu', status: 'complete', startedAt: now, completedAt: now, createdAt: now, questions: [{ id: 'q1', questionText: 'What was home like when you were growing up?', questionOrder: 1, answeredAt: now }], recordings: [{ id: 'recording_sample', originalFilename: 'maya-story-sample.webm', mimeType: 'audio/webm', durationSeconds: 126, fileSize: 248000, processingStatus: 'completed', transcriptId: 'transcript_sample' }] }],
    timelineEvents: [{ id: 'event_kathmandu', eventTitle: 'A childhood shaped by community', eventDescription: 'Maya remembers growing up surrounded by cousins, neighbors, and shared afternoon tea.', eventDate: null, approximateDateText: 'When she was a child', location: 'Kathmandu', confidence: 0.86, confirmationStatus: 'confirmed', evidenceText: 'Our house was always full of cousins and neighbors. Someone was always bringing tea.' }],
    peopleMentions: [{ id: 'person_daju', fullName: 'Daju', relationship: 'Older brother', description: 'Remembered as a protective older brother.', confidence: 0.74, confirmationStatus: 'unconfirmed' }],
    chapters: [{ id: 'chapter_first', title: 'The House That Was Always Full', chapterOrder: 1, content: 'Maya remembers a home shaped less by quiet rooms than by the people who filled them. Cousins arrived without much notice, neighbors shared tea, and afternoons had a way of becoming small gatherings. Looking back, she describes those days as ordinary in the best sense: a life held together by community.', status: 'approved', generatedAt: now, approvedAt: now, updatedAt: now }], exports: []
  };
}

function getStore(): Store {
  if (!globalStore.__keepsakeStore) globalStore.__keepsakeStore = { projects: new Map([['project_maya', seedProject()]]), transcripts: new Map([['transcript_sample', { id: 'transcript_sample', recordingId: 'recording_sample', rawText: 'Our house was always full of cousins and neighbors. Someone was always bringing tea.', correctedText: 'Our house was always full of cousins and neighbors. Someone was always bringing tea.', language: 'en', processingStatus: 'completed' }]]) };
  return globalStore.__keepsakeStore;
}

export function listProjects(user: AppUser) { return [...getStore().projects.values()].filter((project) => project.ownerId === user.id); }
export function getProject(user: AppUser, id: string) { const project = getStore().projects.get(id); if (!project || project.ownerId !== user.id) return null; return project; }
export function createProject(user: AppUser, input: Pick<BiographyProject, 'title' | 'storytellerName' | 'storytellerRelationship' | 'preferredLanguage'>) {
  const now = new Date().toISOString(); const project: BiographyProject = { ...input, id: createId('project'), ownerId: user.id, status: 'draft', coverImageUrl: null, createdAt: now, updatedAt: now, consent: null, interviews: [], timelineEvents: [], peopleMentions: [], chapters: [], exports: [] }; getStore().projects.set(project.id, project); return project;
}
export function updateProject(user: AppUser, id: string, patch: Partial<BiographyProject>) { const project = getProject(user, id); if (!project) return null; Object.assign(project, patch, { updatedAt: new Date().toISOString() }); return project; }
export function deleteProject(user: AppUser, id: string) { const project = getProject(user, id); if (!project) return false; getStore().projects.delete(id); return true; }
export function addConsent(user: AppUser, id: string, consent: NonNullable<BiographyProject['consent']>) { const project = getProject(user, id); if (!project) return null; project.consent = consent; project.updatedAt = new Date().toISOString(); return project; }
export function addInterview(user: AppUser, id: string, title: string) { const project = getProject(user, id); if (!project) return null; const interview: InterviewSession = { id: createId('session'), title, status: 'planned', startedAt: null, completedAt: null, createdAt: new Date().toISOString(), questions: [], recordings: [] }; project.interviews.unshift(interview); return interview; }
export function getInterview(user: AppUser, sessionId: string) { return listProjects(user).flatMap((p) => p.interviews.map((i) => ({ project: p, interview: i }))).find((x) => x.interview.id === sessionId) ?? null; }
export function addQuestions(user: AppUser, sessionId: string) { const found = getInterview(user, sessionId); if (!found) return null; found.interview.questions = ['What was home like when you were growing up?', 'Who made you feel safe and loved?', 'What is one lesson you want your family to carry forward?'].map((questionText, index) => ({ id: createId('question'), questionText, questionOrder: index + 1, answeredAt: null })); return found.interview; }
export function addRecording(user: AppUser, sessionId: string, input: Omit<Recording, 'id' | 'processingStatus' | 'transcriptId'>) { const found = getInterview(user, sessionId); if (!found || !found.project.consent?.recordingConsent) return null; const recording: Recording = { ...input, id: createId('recording'), processingStatus: 'queued', transcriptId: null }; found.interview.recordings.unshift(recording); found.interview.status = 'processing'; return recording; }
export function transcribe(user: AppUser, recordingId: string) { const found = listProjects(user).flatMap((p) => p.interviews.flatMap((i) => i.recordings.map((r) => ({ project: p, interview: i, recording: r })))).find((x) => x.recording.id === recordingId); if (!found) return null; const transcriptId = createId('transcript'); getStore().transcripts.set(transcriptId, { id: transcriptId, recordingId, rawText: 'When I was a child, our home in Kathmandu was always full of cousins and neighbors. My brother Daju taught me to be brave and kind.', correctedText: 'When I was a child, our home in Kathmandu was always full of cousins and neighbors. My brother Daju taught me to be brave and kind.', language: 'en', processingStatus: 'completed' }); found.recording.processingStatus = 'completed'; found.recording.transcriptId = transcriptId; found.interview.status = 'complete'; return getStore().transcripts.get(transcriptId)!;
}
export function extractTimeline(user: AppUser, id: string) { const project = getProject(user, id); if (!project) return null; if (!project.timelineEvents.length) { project.timelineEvents.push({ id: createId('event'), eventTitle: 'Learning courage at home', eventDescription: 'Maya remembers her older brother teaching her to be brave and kind.', eventDate: null, approximateDateText: 'When she was a child', location: 'Kathmandu', confidence: 0.82, confirmationStatus: 'unconfirmed', evidenceText: 'My brother Daju taught me to be brave and kind.' }); project.peopleMentions.push({ id: createId('person'), fullName: 'Daju', relationship: 'Older brother', description: 'A brother who taught Maya to be brave and kind.', confidence: 0.81, confirmationStatus: 'unconfirmed' }); } return project; }
export function confirmTimeline(user: AppUser, eventId: string, status: TimelineEvent['confirmationStatus']) { const found = listProjects(user).flatMap((p) => p.timelineEvents.map((event) => ({ project: p, event }))).find((x) => x.event.id === eventId); if (!found) return null; found.event.confirmationStatus = status; return found.event; }
export function generateChapter(user: AppUser, id: string) { const project = getProject(user, id); if (!project) return null; const chapter: Chapter = { id: createId('chapter'), title: project.timelineEvents[0]?.eventTitle ?? 'A Life in Memories', chapterOrder: project.chapters.length + 1, content: `Maya remembers ${project.timelineEvents[0]?.eventDescription.toLowerCase() ?? 'the moments that shaped her family'}.\n\nThe details are still close: ${project.timelineEvents[0]?.evidenceText ?? 'a story shared in her own words'}. This first chapter keeps her voice at the center and leaves room for the memories still to come.`, status: 'needs_review', generatedAt: new Date().toISOString(), approvedAt: null, updatedAt: new Date().toISOString() }; project.chapters.push(chapter); project.status = 'in_progress'; return chapter; }
export function updateChapter(user: AppUser, chapterId: string, content: string) { const found = listProjects(user).flatMap((p) => p.chapters.map((chapter) => ({ project: p, chapter }))).find((x) => x.chapter.id === chapterId); if (!found) return null; found.chapter.content = content; found.chapter.updatedAt = new Date().toISOString(); return found.chapter; }
export function approveChapter(user: AppUser, chapterId: string) { const found = listProjects(user).flatMap((p) => p.chapters.map((chapter) => ({ project: p, chapter }))).find((x) => x.chapter.id === chapterId); if (!found) return null; found.chapter.status = 'approved'; found.chapter.approvedAt = new Date().toISOString(); return found.chapter; }
export function addExport(user: AppUser, id: string, job: ExportJob) { const project = getProject(user, id); if (!project) return null; project.exports.unshift(job); return job; }
export function getExport(user: AppUser, exportId: string) { return listProjects(user).flatMap((p) => p.exports.map((job) => ({ project: p, job }))).find((x) => x.job.id === exportId) ?? null; }
